---
title: ''
author: 'Lillian Gorman Sanisaca'
date: "`r paste0('Report Generated : ',format(Sys.time(), '%m-%d-%Y'))`"
output: html_document
params:
  libraryPath: libraryPath
  BGfilePath: BGfilePath
  SGfilePath: SGfilePath
  plotName: plotName
  paramList: parmList
  plotType: plotType
  seqType: seqType
  seqLength: seqLength
  period: period
  removeDates: removeDates
---
<style>
    body .main-container {
        max-width: 1000px;
    }
</style>

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,fig.width=12, fig.height=8, warning = FALSE, message = FALSE)

```
 
```{r, eval=TRUE, warning=FALSE, message=FALSE, include=FALSE}
#setPaths
libraryPath<-params$libraryPath
BGfilePath<-params$BGfilePath
SGfilePath<-params$SGfilePath
plotName<-params$plotName
parmList<-params$parmList
plotType<-params$plotType
seqType<-params$seqType
seqLength<-params$seqLength
period<-params$period
removeDates<-params$removeDates

#load functions
suppressWarnings(suppressMessages(devtools::load_all(libraryPath,recompile = FALSE)))

#get pumpSettings
pumpSettings.list<-makePumpSettings(libraryPath)
unPackList(lists = list(pumpSettings.list = pumpSettings.list),
           parentObj = list(NA)) 

#csv data import
dataImport.list<-dataImport(BGfilePath,SGfilePath,libraryPath)
unPackList(lists = list(dataImport.list = dataImport.list),
           parentObj = list(NA)) 
data<-allData

  if (seqType=='change'){
  #get pumpSettings
  pumpSettings.list<-makePumpSettings(libraryPath)
  unPackList(lists = list(pumpSettings.list = pumpSettings.list),
             parentObj = list(NA)) 
  dateSeq<-.Date(0)
  dateSeq<-dateSeq[0]
  for (s in names(pumpSettings.list)){
    eval(parse(text = paste0('temp<-pumpSettings.list$',s)))
    dateStr<-gsub('X','',names(temp)[2:length(temp)])
  dateStr<-gsub('\\.','-',dateStr)
  dateStr<-as.Date(dateStr,format = '%m-%d-%Y',origin = '1970-01-01')
    dateSeq<-c(dateSeq,dateStr)
  }
  dateSeq<-c(as.Date(max(data$Date), format = "%Y-%m-%d"),dateSeq) 
  dateSeq<-unique(dateSeq)
  dateSeq<-dateSeq[order(dateSeq, decreasing = TRUE)]
  dateSeq<-dateSeq[dateSeq<=max(data$Date2)]
  }else{#if seqType = days
dateSeq<-seq.Date(from = max(data$Date2),to = min(data$Date2),by=paste0('-',period,' day'))

}

  #trim dateSeq
if (seqLength!='all' & seqType=='change'){
  if (length(dateSeq)>seqLength+1){

    dateSeq<-dateSeq[1:(seqLength+1)]
  }
}else if (seqType!='change' & seqLength!='all'){
          if (length(dateSeq)<seqLength+1){
    dateSeq<-c(dateSeq,min(data$Date2))
          }else{
            dateSeq<-dateSeq[1:(seqLength+1)]
          }
    }
 

  #plot each pair

rmd <- sapply(
  1:(length(dateSeq)-1),
  function(d) {
    knit_expand(paste0(libraryPath,"reports/historySeqChild.Rmd"), d = d)
  }
)
rmd <- paste(rmd, collapse = "\n")

```

```{r  echo=FALSE, results='asis', warning=FALSE, message=FALSE}
rendered <- knit(text = rmd, quiet = TRUE)
cat("\n \n")
cat(rendered, sep = "\n")
```
